name: Update Environment Git Tag
description: Commit all kustomization.yaml file changes in the k8s/ directory to the Default Branch
inputs:
  tag:
    description: Git Tag Name
    required: true
  ref:
    description: Git Reference
    required: true
runs:
  using: composite
  steps:
    - run: make -Bf ${{ github.action_path }}/Makefile TAG="${{ github.event.inputs.tag }}" REF="${{ github.event.inputs.ref }}" print
      shell: bash
